# Generated by Django 4.1.7 on 2023-03-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='number',
        ),
        migrations.AddField(
            model_name='report',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
