# Generated by Django 4.1.7 on 2023-03-29 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_report_remove_uploadimage_caption_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='comment',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='phone',
            field=models.CharField(default='', max_length=10),
        ),
    ]
