# Generated by Django 4.1.7 on 2023-03-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_uploadimage_comment_alter_uploadimage_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
